### ISSUE TITLE
Does a Rust package require a C compiler?

### ISSUE THREAD

**Issue by darynwhite** [conda-forge/tsdownsample-feedstock#5]
https://github.com/conda-forge/tsdownsample-feedstock/blob/ad28b2c6af5a4bcaa56fb2d7928f64a84d9b4a08/recipe/meta.yaml#L19

**Comment by thewchan** [comment]
Yes

**Comment by thewchan** [comment]
to be fair, I'm not 100% sure this is universal, but it's required in this case and in my experience in all rust/python/maturin package I've dealt with on conda forge

**Comment by darynwhite** [comment]
When I began working on getting this online, I didn't include it and it didn't seem to need it. https://github.com/conda-forge/staged-recipes/pull/23550/checks

BUT it did need the nightly Rust build; which you addressed.
